package config

import (
	"strings"
	"testing"
)

// This file answers one question for the containment subjects: is a given marker written inside a
// value the schema declares sensitive? A layout's own claim about where it hid a secret is an
// assumption about bytes it wrote, and generated bytes can falsify it -- a closer in a tail can
// close the container a layout left open, and the remainder then lands in a comment the parser
// places outside every value. Recomputing the extents from the document is what lets such a plant
// still assert the contract rather than be abandoned.

// sensitiveExtentsOf is every region the schema declares sensitive in a document that parses,
// derived from the table and the parser's own paths by containmentschemaoracle_test.go.
//
// It used to be the production walk's own output, which made every question below a question about
// what that walk had already decided. The document is still prepared exactly as the redactor
// prepares it -- parsed, and normalized so an alias points at the node its anchor defined -- because
// the oracle has to read the tree the redactor read; what it may not inherit is the attribution.
func sensitiveExtentsOf(t *testing.T, text *source) ([]declaredSensitiveExtent, bool) {
	t.Helper()

	root, diags := parseDocument(text)
	if !pathsAreResolvable(root, diags) {
		return nil, false
	}

	// Stage E's diagnostics belong to the caller's own run, exactly as the redactor discards them.
	_ = normalize(text, root)
	return declaredSensitiveExtentsOf(text, root), true
}

// lineHoldingMarker is the 1-based line of text that holds the marker, or notOnAnyLine when none
// does. A marker the document never received must not be able to satisfy an extent test by being
// nowhere, so both callers below distinguish the two cases rather than sharing one answer.
func lineHoldingMarker(text *source, marker string) int {
	for number := firstLine; number <= len(text.lines); number++ {
		if strings.Contains(text.Line(number), marker) {
			return number
		}
	}
	return notOnAnyLine
}

const notOnAnyLine = 0

// insideASensitiveExtent reports whether the marker is written inside a value the schema declares
// sensitive: within the value's own text, or on a line the value wholly covers.
//
// A value's first and last lines are covered only where its own text lies, which is why they are not
// claimed by the line rule. Both are lines the value *shares*, and what it shares them with is not
// its own: `- ` followed by a comment is a null node anchored on that comment's line, and `secrets:
// [A]#B` -- a generated `]` closing the container early -- puts B in a comment beside a value that
// ended at the bracket. Claiming either would require a comment's bytes to disappear, while
// redactValue quite correctly leaves them, so the oracle would report a leak the redactor did not
// commit.
//
// The text rule carries the weight, and it is what makes the narrowing safe: a value the redactor
// rendered instead of replacing is found by its own bytes wherever it was written. What the line rule
// adds is the interior of a multi-line value, whose lines hold nothing else.
//
// One claim this cannot make is the layout's own: that an ordinary tail sharing a *physical* line
// with a secret goes with it. That is not a schema extent, and it is asserted where it belongs -- by
// the deterministic grid, which runs every layout, and by
// TestBothRedactionBranchesCoverAValueEndingAtACarriageReturn.
func insideASensitiveExtent(text *source, found []declaredSensitiveExtent, marker string) bool {
	line := lineHoldingMarker(text, marker)
	if line == notOnAnyLine {
		return false
	}

	at := columnOfMarker(text.Line(line), marker)
	for _, value := range found {
		if withinExtent(value, line, at) {
			return true
		}
	}
	return false
}

// withinExtent reports whether one rune column of one line lies in an extent's half-open span. An
// interior line belongs whole; the first and last lines belong from and up to the columns the value
// itself occupies, which is what keeps a sibling key written before a flow container and a comment
// written past its closer outside a question about the container.
func withinExtent(value declaredSensitiveExtent, line int, at columnInRunes) bool {
	if line < value.line || line > value.through {
		return false
	}
	if line > value.line && line < value.through {
		return true
	}
	return (line > value.line || at >= value.from) && (line < value.through || at < value.past)
}

// columnOfMarker is the rune column a marker begins at on the line holding it. The column is
// counted in runes because that is the unit every extent is expressed in; counting bytes would
// place a marker written after a multi-byte rune past where the value actually ends.
func columnOfMarker(written, marker string) columnInRunes {
	return firstColumn + columnInRunes(runeCount(written[:strings.Index(written, marker)]))
}

// assertNoMarkerInsideASensitiveValueSurvives is the containment contract recomputed from the
// document, for a plant whose generated tail moved it to the branch its layout did not declare.
// Only the markers the document actually places inside a declared-sensitive value are required to
// be absent, so the claim is the redactor's contract rather than the layout's assumption.
func assertNoMarkerInsideASensitiveValueSurvives(t *testing.T, planted plantedSecret) {
	t.Helper()

	text := newSource("listeners.yaml", []byte(planted.text))
	found, parses := sensitiveExtentsOf(t, text)
	if !parses {
		// The document no longer parses, so which bytes are sensitive is exactly what cannot be
		// read from it -- the reason the key-scoped fallback exists at all. Its own over-redaction
		// is asserted by the fallback grid rather than guessed at here.
		return
	}

	rendered := renderEveryLineOf(planted.text)
	for _, marker := range planted.markers {
		if !insideASensitiveExtent(text, found, marker) {
			continue
		}
		if strings.Contains(rendered, marker) {
			t.Errorf("%s: a generated tail moved this plant to the other branch and %s is still inside "+
				"a declared-sensitive value, yet was rendered\nsource:\n%s\nrendered:\n%s",
				planted.where, marker, planted.text, rendered)
		}
	}
}
