package config

import (
	"regexp"
	"strings"
)

type diagnosticContractSignal struct {
	matcher *regexp.Regexp
	example string
}

func exactDiagnostic(message string) diagnosticContractSignal {
	example := strings.ToLower(message)
	return diagnosticContractSignal{
		matcher: regexp.MustCompile("^" + regexp.QuoteMeta(example) + "$"),
		example: example,
	}
}

func shapedDiagnostic(pattern, example string) diagnosticContractSignal {
	return diagnosticContractSignal{
		matcher: regexp.MustCompile("^(?:" + pattern + ")$"),
		example: strings.ToLower(example),
	}
}

var numberedDiagnosticContractSignals = map[RuleID][]diagnosticContractSignal{
	R1: {exactDiagnostic(`missing required key "version"`), exactDiagnostic("must equal 1")},
	R2: {shapedDiagnostic(
		`must match \^\[a-z\]\[a-z0-9_\]\{0,40\}\$: (?:empty|illegal character|over the character limit)`,
		`must match ^[a-z][a-z0-9_]{0,40}$: illegal character`)},
	R3: {
		exactDiagnostic(`missing required key "database.url"`),
		exactDiagnostic("must be a postgres or postgresql URI, or a libpq keyword/value connection string"),
	},
	R4: {
		shapedDiagnostic(
			`must be a postgresql identifier of at most 63 bytes: (?:empty|illegal character|over the byte limit)`,
			"must be a PostgreSQL identifier of at most 63 bytes: illegal character"),
		exactDiagnostic(`the prefix "pg_" is reserved for system schemas`),
	},
	R5:  {exactDiagnostic("must be a postgres or postgresql URI, or a libpq keyword/value connection string")},
	R6:  {exactDiagnostic("must be in the range 1 to 1024")},
	R7:  {exactDiagnostic("must be in the range 1 to 10000")},
	R8:  {exactDiagnostic("must be greater than zero")},
	R9:  {exactDiagnostic("worker.lease_timeout must be greater than the largest effective listeners[].timeout; increase the lease or lower the timeout because a lease no longer than a request timeout causes duplicate deliveries")},
	R10: {exactDiagnostic("must be greater than zero")},
	R11: {exactDiagnostic("retention.keep must be at least retention.partition_interval; increase retention.keep or lower retention.partition_interval")},
	R12: {exactDiagnostic("retention.precreate must be at least retention.partition_interval; increase retention.precreate or lower retention.partition_interval")},
	R13: {exactDiagnostic("must be greater than zero")},
	R14: {exactDiagnostic("must be at least 1")},
	R15: {exactDiagnostic("must be one of exponential, linear or fixed")},
	R16: {exactDiagnostic("retry.initial_interval must be no greater than retry.max_interval; lower retry.initial_interval or raise retry.max_interval")},
	R17: {exactDiagnostic("must be greater than zero")},
	R18: {exactDiagnostic("expected true or false")},
	R19: {
		exactDiagnostic("header name must be a valid HTTP field name"),
		exactDiagnostic("header value must not be empty"),
	},
	R20: {shapedDiagnostic(
		`header ".*" differs only in case from the one on line [1-9][0-9]*`,
		`header "x-trace-id" differs only in case from the one on line 8`)},
	R21: {exactDiagnostic(`headers beginning with "x-pg-noty-" are generated by pg_noty itself`)},
	R22: {exactDiagnostic(`missing required key "listeners"`)},
	R23: {
		exactDiagnostic(`missing required key "name"`),
		shapedDiagnostic(
			`must match \^\[a-z\]\[a-z0-9_\]\{0,40\}\$: (?:empty|illegal character|over the character limit)`,
			`must match ^[a-z][a-z0-9_]{0,40}$: illegal character`),
	},
	R24: {shapedDiagnostic(
		`must be unique; the first listener with this name is on line [1-9][0-9]*`,
		"must be unique; the first listener with this name is on line 8")},
	R25: {exactDiagnostic("expected true or false")},
	R26: {
		exactDiagnostic(`missing required key "table"`),
		exactDiagnostic("must be schema-qualified in schema.table form"),
		shapedDiagnostic(
			`schema part must be a postgresql identifier of at most 63 bytes: (?:empty|illegal character|over the byte limit)`,
			"schema part must be a PostgreSQL identifier of at most 63 bytes: illegal character"),
		shapedDiagnostic(
			`table part must be a postgresql identifier of at most 63 bytes: (?:empty|illegal character|over the byte limit)`,
			"table part must be a PostgreSQL identifier of at most 63 bytes: over the byte limit"),
	},
	R27: {exactDiagnostic(`"operations" must hold at least one entry`)},
	R28: {shapedDiagnostic(`unknown field ".*"`, `unknown field "truncate"`)},
	R29: {
		exactDiagnostic(`"columns" is legal only under "update"`),
		exactDiagnostic(`"columns" must hold at least one entry`),
		shapedDiagnostic(
			`entry duplicates the one first written on line [1-9][0-9]*`,
			"entry duplicates the one first written on line 8"),
		shapedDiagnostic(
			`must be a postgresql identifier of at most 63 bytes: (?:empty|illegal character|over the byte limit)`,
			"must be a PostgreSQL identifier of at most 63 bytes: empty"),
	},
	R30: {
		exactDiagnostic("delete trigger's WHEN condition cannot reference NEW values"),
		exactDiagnostic("insert trigger's WHEN condition cannot reference OLD values"),
	},
	R31: {exactDiagnostic("must be one of full, columns or keys_only")},
	R32: {
		shapedDiagnostic(`entry duplicates the one first written on line [1-9][0-9]*`,
			"entry duplicates the one first written on line 8"),
		shapedDiagnostic(
			`must be a postgresql identifier of at most 63 bytes: (?:empty|illegal character|over the byte limit)`,
			"must be a PostgreSQL identifier of at most 63 bytes: empty"),
		exactDiagnostic("must hold at least one identifier"),
		exactDiagnostic("payload.columns is legal only when payload.mode is columns"),
		exactDiagnostic("payload.columns is required when payload.mode is columns"),
	},
	R33: {
		shapedDiagnostic(`entry duplicates the one first written on line [1-9][0-9]*`,
			"entry duplicates the one first written on line 8"),
		shapedDiagnostic(
			`must be a postgresql identifier of at most 63 bytes: (?:empty|illegal character|over the byte limit)`,
			"must be a PostgreSQL identifier of at most 63 bytes: illegal character"),
		exactDiagnostic("payload.columns and payload.exclude are mutually exclusive"),
		exactDiagnostic("payload.exclude is legal only when payload.mode is full"),
	},
	R34: {exactDiagnostic("expected true or false")},
	R35: {exactDiagnostic("must be greater than zero")},
	R36: {
		exactDiagnostic(`missing required key "destination.url"`),
		shapedDiagnostic(
			`must be a non-empty http or https url with a host: (?:empty|no host|scheme is neither http nor https|does not parse: .+)`,
			"must be a non-empty http or https URL with a host: scheme is neither http nor https"),
	},
	R37: {exactDiagnostic("must be one of POST, PUT or PATCH")},
	R38: {
		shapedDiagnostic(`entry duplicates the one first written on line [1-9][0-9]*`,
			"entry duplicates the one first written on line 8"),
		exactDiagnostic("signing secret must not be empty"),
	},
	R39: {
		exactDiagnostic("must be in the range 1 to 1024"),
		exactDiagnostic("listeners[].concurrency must be no greater than worker.concurrency; lower the listener concurrency or raise worker.concurrency"),
	},
	R40: {exactDiagnostic("must use a Go duration with units ns, us/µs, ms, s, m or h")},
	R41: {shapedDiagnostic(`unknown field ".*"`, `unknown field "colums"`)},
	R42: {shapedDiagnostic(
		`mapping key ".*" already defined at \[[1-9][0-9]*:[1-9][0-9]*\]`,
		`mapping key "schema" already defined at [2:3]`)},
	R43: {
		exactDiagnostic(`"is_distinct" is legal only under "update"`),
		exactDiagnostic("expected true or false"),
	},
}
