package config

import (
	"strings"
	"testing"
	"unicode/utf8"
)

func TestStructuredScalarRulesRejectTheirOutsideClassOnce(t *testing.T) {
	base := listenerHolding("")
	tests := []struct {
		name, document, token, path, message string
		occurrence                           int
		rule                                 RuleID
	}{
		{"database url", replaceOnce(t, base, "postgres://noty:pw@db.internal:5432/noty", "not-a-connection"),
			"not-a-connection", "database.url", "keyword/value", 1, R3},
		{"listen url", strings.Replace(base, "  url: postgres://noty:pw@db.internal:5432/noty\n",
			"  url: postgres://noty:pw@db.internal:5432/noty\n  listen_url: 1=2\n", 1),
			"1=2", "database.listen_url", "keyword/value", 1, R5},
		{"unqualified table", replaceOnce(t, base, "public.orders", "orders"),
			"orders", "listeners[0].table", "schema-qualified", 1, R26},
		{"bad table part", replaceOnce(t, base, "public.orders", "bad-name.orders"),
			"bad-name.orders", "listeners[0].table", "schema part", 1, R26},
		{"unsupported destination scheme", replaceOnce(t, base,
			"https://hooks.example.test/order-paid", "ftp://host/x"),
			"ftp://host/x", "listeners[0].destination.url", "http", 1, R36},
		{"unparseable destination", replaceOnce(t, base,
			"https://hooks.example.test/order-paid", `"http://[::1"`),
			`"http://[::1"`, "listeners[0].destination.url", "parse", 1, R36},
		{"destination without host", replaceOnce(t, base,
			"https://hooks.example.test/order-paid", "http:///hook"),
			"http:///hook", "listeners[0].destination.url", "host", 1, R36},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			assertStructuredDiagnostic(t, tc.document, tc.rule, tc.path, tc.token, tc.occurrence, tc.message)
		})
	}
}

func TestHeaderRulesCoverBothHeaderExtents(t *testing.T) {
	tests := []struct {
		name, document, path, token, message string
		rule                                 RuleID
	}{
		{"invalid default name", strings.Replace(listenerHolding(""), "listeners:\n",
			"defaults:\n  headers:\n    Bad Header: value\nlisteners:\n", 1),
			"defaults.headers.Bad Header", "Bad Header", "HTTP field", R19},
		{"invalid destination name", destinationOf("    destination:\n" +
			"      url: https://hooks.example.test/order-paid\n" +
			"      headers:\n        Bad Header: value\n"),
			"listeners[0].destination.headers.Bad Header", "Bad Header", "HTTP field", R19},
		{"empty default value", strings.Replace(listenerHolding(""), "listeners:\n",
			"defaults:\n  headers:\n    X-Trace: \"\"\nlisteners:\n", 1),
			"defaults.headers.X-Trace", `""`, "empty", R19},
		{"empty destination value", destinationOf("    destination:\n" +
			"      url: https://hooks.example.test/order-paid\n" +
			"      headers:\n        X-Trace: \"\"\n"),
			"listeners[0].destination.headers.X-Trace", `""`, "empty", R19},
		{"reserved default name", strings.Replace(listenerHolding(""), "listeners:\n",
			"defaults:\n  headers:\n    X-Pg-Noty-Event-Id: mine\nlisteners:\n", 1),
			"defaults.headers.X-Pg-Noty-Event-Id",
			"X-Pg-Noty-Event-Id", "generated by pg_noty", R21},
		{"reserved destination name", destinationOf("    destination:\n" +
			"      url: https://hooks.example.test/order-paid\n" +
			"      headers:\n        X-Pg-Noty-Event-Id: mine\n"),
			"listeners[0].destination.headers.X-Pg-Noty-Event-Id",
			"X-Pg-Noty-Event-Id", "generated by pg_noty", R21},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			assertStructuredDiagnostic(t, tc.document, tc.rule, tc.path, tc.token, 1, tc.message)
		})
	}
}

func TestListenerNameUniquenessReportsTheSecondOccurrence(t *testing.T) {
	document := configAround("  - name: repeated_name\n" +
		"    table: public.orders\n    operations: [insert]\n" +
		"    destination:\n      url: https://one.example/hook\n" +
		"  - name: repeated_name\n" +
		"    table: public.archive\n    operations: [delete]\n" +
		"    destination:\n      url: https://two.example/hook\n")
	assertStructuredDiagnostic(t, document, R24, "listeners[1].name", "repeated_name", 2, "first")
}

func TestStructuredScalarRulesAcceptTheirInsideClass(t *testing.T) {
	sixtyThree := strings.Repeat("a", maxIdentifierBytes)
	document := strings.Replace(listenerHolding(""), "public.orders", "public."+sixtyThree, 1)
	document = strings.Replace(document, "database:\n", "database:\n  listen_url: host=replica dbname=noty\n", 1)
	if _, diags := stageH(t, document); len(diags) != 0 {
		t.Fatalf("valid structured values produced %q", messagesOf(diags))
	}
}

func assertStructuredDiagnostic(
	t *testing.T, document string, rule RuleID, path, token string, occurrence int, message string,
) {
	t.Helper()
	_, diags := stageH(t, document)
	if len(diags) != 1 {
		t.Fatalf("got %d diagnostics %q, want exactly one", len(diags), messagesOf(diags))
	}
	got := diags[0]
	if got.Rule != rule || got.Path != path || !strings.Contains(got.Msg, message) {
		t.Errorf("diagnostic = %+v, want %s at %s containing %q", got, rule, path, message)
	}
	line, column := occurrencePosition(t, document, token, occurrence)
	if got.Line != line || got.Col != column {
		t.Errorf("diagnostic is at %d:%d, want token %q at %d:%d",
			got.Line, got.Col, token, line, column)
	}
}

func occurrencePosition(t *testing.T, document, token string, occurrence int) (int, int) {
	t.Helper()
	remaining := occurrence
	for lineNumber, line := range strings.Split(document, "\n") {
		for from := 0; ; {
			at := strings.Index(line[from:], token)
			if at < 0 {
				break
			}
			at += from
			remaining--
			if remaining == 0 {
				return lineNumber + 1, utf8.RuneCountInString(line[:at]) + 1
			}
			from = at + len(token)
		}
	}
	t.Fatalf("occurrence %d of %q not found", occurrence, token)
	return 0, 0
}
