package config

import (
	"fmt"
	"strings"
)

func (v *validatePass) validateConnection(rule RuleID, value Str) {
	if !value.Valid() {
		return
	}
	form := connectionStringForm(value.value)
	if form == connStringInvalid {
		v.reportStructured(rule, value, semanticFault(
			"must be a postgres or postgresql URI, or a libpq keyword/value connection string"))
	}
}

func (v *validatePass) validateTable(value Str) {
	if !value.Valid() {
		return
	}
	part, defect := qualifiedTableFault(value.value)
	var message string
	switch part {
	case tableNotQualified:
		message = "must be schema-qualified in schema.table form"
	case tableSchemaPartInvalid, tableNamePartInvalid:
		message = fmt.Sprintf("%s must be a PostgreSQL identifier of at most %d bytes: %s",
			part, maxIdentifierBytes, defect)
	default:
		return
	}
	v.reportStructured(R26, value, semanticFault(message))
}

func (v *validatePass) validateListenerNames(listeners []rawListener) {
	first := make(map[string]Str, len(listeners))
	for i := range listeners {
		name := listeners[i].Name
		if !name.Valid() {
			continue
		}
		if prior, duplicate := first[name.value]; duplicate {
			v.reportStructured(R24, name, semanticFault(fmt.Sprintf(
				"must be unique; the first listener with this name is on line %d", prior.Line())))
			continue
		}
		first[name.value] = name
	}
}

func (v *validatePass) validateHeaders(headers rawHeaders) {
	for i := range headers.values {
		header := headers.values[i]
		canonical, validName := canonicalHTTPFieldName(header.Name.value)
		if !validName {
			v.reportHeader(R19, headerNameUse, header, semanticFault(
				"header name must be a valid HTTP field name"))
		} else if usesReservedHeaderPrefix(canonical) {
			v.reportHeader(R21, headerNameUse, header, semanticFault(fmt.Sprintf(
				"headers beginning with %q are generated by pg_noty itself", reservedHeaderPrefix)))
		}
		if header.Value.Valid() && header.Value.value == "" {
			v.reportHeader(R19, headerValueUse, header, semanticFault(
				"header value must not be empty"))
		}
	}
}

func (v *validatePass) validateOperations(operations rawOperations) {
	for i := range operations.values {
		named := operations.values[i]
		if named.Name.value == updateOperation {
			v.validateIdentifierList(R29, named.Filter.Columns, false)
		}
		if !named.Filter.When.Valid() {
			continue
		}
		ref, forbidden := forbiddenWhenReference(named.Name.value, named.Filter.When.value)
		if forbidden {
			v.reportStructured(R30, named.Filter.When, semanticFault(fmt.Sprintf(
				"%s trigger's WHEN condition cannot reference %s values", ref.Statement, ref.Word)))
		}
	}
}

func (v *validatePass) validateDestination(raw rawDestination) {
	v.validateDestinationURL(raw.URL)
	v.oneOf(R37, raw.Method, destinationMethods)
	v.validateHeaders(raw.Headers)
	v.validateSigningSecrets(raw.Signing.Value.Secrets)
}

func (v *validatePass) validateDestinationURL(value Str) {
	if !value.Valid() {
		return
	}
	defect, reason := destinationURLDefect(value.value)
	if defect == urlOK {
		return
	}
	message := fmt.Sprintf("must be a non-empty http or https URL with a host: %s", defect)
	if reason != "" {
		message += ": " + reason
	}
	v.reportStructured(R36, value, semanticFault(message))
}

func (v *validatePass) reportStructured(rule RuleID, value Positioned, why fault) {
	reportSemanticUsing(&v.stage, rule, structuredValueUse, anchorSet{value: value}, why)
}

func (v *validatePass) reportHeader(
	rule RuleID, use semanticAnchorUse, header writtenHeader, why fault,
) {
	reportSemanticUsing(&v.stage, rule, use, anchorSet{
		key: header.Name, value: header.Value,
	}, why)
}

func readableList(values []string) string {
	if len(values) < 2 {
		return fmt.Sprint(values)
	}
	return fmt.Sprintf("%s or %s", strings.Join(values[:len(values)-1], ", "), values[len(values)-1])
}
